### PR TITLE
Write response message with one call

### PR DESCRIPTION
**Pull request by JamesNK**

### CODE REVIEW

**Comment by davidfowl** [comment]
This is going to change to use the PipeWriter eventually right?

**Comment by JamesNK** [comment]
Ya-huh

**Comment by JamesNK** [comment]
Note that in preview 2 the PipeWriter is a wrapper over the Stream so that doesn't help.

**Comment by davidfowl** [comment]
> Note that in preview 2 the PipeWriter is a wrapper over the Stream so that doesn't help.

It doesn't matter, you should use it regardless of the implementation. It'll just end up being more efficient in 3.0.

**Comment by JamesNK** [comment]
It matters for now because this has an effect on whether the C# client errors or not. See https://github.com/grpc/grpc/issues/17840

**Comment by davidfowl** [comment]
> It matters for now because the number of DATA sections in the HTTP/2 response has an effect on whether the C# client errors or not. See grpc/grpc#17840

The pipe writer is buffered by default, when you flush is when it'll get written to the stream.

**Comment by JamesNK** [comment]
Will try it out in preview 2.

**Pull request merged**
